export const images = [
  { imgSrc: "/alien.png", name: "alien" },
  { imgSrc: "/blue.png", name: "blue" },
  { imgSrc: "/boy.png", name: "boy" },
  { imgSrc: "/brutus.png", name: "brutus" },
  { imgSrc: "/cartoon.png", name: "cartoon" },
  { imgSrc: "/daphne.png", name: "daphne" },
  { imgSrc: "/fred.png", name: "fred" },
  { imgSrc: "/garnet.png", name: "garnet" },
  { imgSrc: "/greg.png", name: "greg" },
  { imgSrc: "/helper.png", name: "helper" },
  { imgSrc: "/jake.png", name: "jake" },
  { imgSrc: "/jerry.png", name: "jerry" },
  { imgSrc: "/koya.png", name: "koya" },
  { imgSrc: "/mickey.png", name: "mickey" },
  { imgSrc: "/morty.png", name: "morty" },
  { imgSrc: "/plush.png", name: "plush" },
  { imgSrc: "/popeye.png", name: "popeye" },
  { imgSrc: "/rick.png", name: "rick" },
  { imgSrc: "/scooby.png", name: "scooby" },
  { imgSrc: "/shaggy.png", name: "shaggy" },
  { imgSrc: "/sonic.png", name: "sonic" },
  { imgSrc: "/teddy.png", name: "teddy" },
  { imgSrc: "/toroto.png", name: "toroto" },
  { imgSrc: "/transformer.png", name: "transformer" },
];
